### ISSUE TITLE
Don't use list_on_cluster to gather issues

### ISSUE THREAD

**Issue by rosik** [tarantool/metrics#211]
The `cartridge_issues.list_on_cluster` function gathers issues from entire cluster (obviously). The same does prometheus. It results in N^2 network requests. Prometheus queries every instances metrics and for every request, `list_on_cluster` does N more.

I think the metrics module should collect local issues only.

**Comment by ZolotarevIgor-mail-ru** [comment]
I suggest to gather only local issues in this metric and add new metric e.g. `cluster_issues` and API to enable cluster issues only. It could be called on instances with special role (e.g. router)

**Comment by ZolotarevIgor-mail-ru** [comment]
After some discussion we decided not to change this metric behavior and add function to disable that metric.

**Comment by rosik** [comment]
Will you leave it enabled by default?

**Comment by olegrok** [comment]
> After some discussion we decided not to change this metric behaviour and add function to disable that metric.

I just share some details that we recently faced when try to deploy huge cluster.
There where several hundreds instances on one physical hosts. So one moment each Tarantool instance had established connections to each instance in our cluster. The problem is that amount of ports is limited. Finally, we lost an ability to connect to our host and there are some problems when Tarantools try to connect to each other (e.g. for replication).

Is it our official position to consume all available ports? @vasiliy-t @ZolotarevIgor-mail-ru I suggest to reconsider your opinion about this issue. Actually it's a bug, not "refactoring".
