### ISSUE TITLE
Could you please add metric for trigger count on spaces 

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/metrics#272]
There is situation when user reload such code several times

```
box.space[name]:before_replace(triggerfunc)
```

This way trigger become as many as code executed.

Consider to export metric with space trigger count

```
#box.space.test:on_replace()
```

**Comment by rosik** [comment]
I think this metric is useless for monitoring. As far as I understand, the origin of this proposal is a recent bug in the client application apply config when triggers were never removed. That was a bug, but the metrics module isn't suitable for searching bugs in code.

The proposed metric is also useless because in the correct code it should always be constant. And constant metric isn't a good metric.
