### ISSUE TITLE
HTTP latency collector start

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#96]
HTTP latency collector starts working only on first processed request, before it it's `null rps`, not `0 rps`.

**Comment by DifferentialOrange** [comment]
Check if behavior is the same in summary collector, introduced in #101 .

**Comment by yngvar-antonsson** [comment]
I think it is valid behavior, because before first processed request we don't know labels to set to collector.

Official Prometheus clients don't provide default values for summary and histogram.
It doesn't relate to #260 / #288 . According to Prometheus API docs, counter _may_ be reset to zero. 

I propose to close this issue.

**Comment by DifferentialOrange** [comment]
Well, OK, seems legit
